ADDED_TO_SCENE = "ADDED_TO_SCENE"
BOOT = "BOOT"
CREATE = "CREATE"
TEARDOWN = "TEARDOWN"
PAUSE = "PAUSE"
PRE_RENDER = "PRE_RENDER"
POST_RENDER = "POST_RENDER"
PRE_UPDATE = "PRE_UPDATE"
POST_UPDATE = "POST_UPDATE"
READY = "READY"
REMOVED_FROM_SCENE = "REMOVED_FROM_SCENE"
RENDER = "RENDER"
RESUME = "RESUME"
SHUTDOWN = "SHUTDOWN"
SLEEP = "SLEEP"
START = "START"
TRANSITION_COMPLETE = "TRANSITION_COMPLETE"
TRANSITION_INIT = "TRANSITION_INIT"
TRANSITION_OUT = "TRANSITION_OUT"
TRANSITION_START = "TRANSITION_START"
UPDATE = "UPDATE"
WAKE = "WAKE"

__all__ = [
    "ADDED_TO_SCENE",
    "BOOT",
    "CREATE",
    "TEARDOWN",
    "PAUSE",
    "PRE_RENDER",
    "POST_RENDER",
    "PRE_UPDATE",
    "POST_UPDATE",
    "READY",
    "REMOVED_FROM_SCENE",
    "RENDER",
    "RESUME",
    "SHUTDOWN",
    "SLEEP",
    "START",
    "TRANSITION_COMPLETE",
    "TRANSITION_INIT",
    "TRANSITION_OUT",
    "TRANSITION_START",
    "UPDATE",
    "WAKE",
]
